{{- if .Values.additionalScrapeConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs-{{ .Values.instanceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: additional-scrape-configs-{{ .Values.instanceName }}
{{ include "prometheus.labels" . | indent 4 }}
{{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
data:
  additional-scrape-configs.yaml: {{ tpl (toYaml .Values.additionalScrapeConfigs) $ | b64enc | quote }}
{{- end }}