apiVersion: v1
kind: Service
metadata:
  name: prometheus-{{- .Values.instanceName }}-service
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}

  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      port: 9090
      protocol: TCP
      targetPort: web
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}