{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.serviceAccountName" . }}
  namespace: {{ template "prometheus-operator.namespace" . }}
  labels:
    app: {{ template "prometheus-operator.name" . }}
    app.kubernetes.io/name: {{ template "prometheus-operator.name" . }}
    app.kubernetes.io/component: prometheus-operator
{{ include "prometheus-operator.labels" . | indent 4 }}
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{ include "prometheus-operator.imagePullSecrets" . | trim | indent 2 }}
{{- end }}
{{- end }}