apiVersion: v2
name: prometheus-operator
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
description: Stripped down version of prometheus-operator to only provision the operator and nothing else based on the kube-prometheus-stack chart. 

type: application

version: 1.0.2

appVersion: 0.59.2

kubeVersion: ">=1.16.0-0"
home: https://github.com/arldka/helm-charts
keywords:
  - operator
  - prometheus
  - prometheus-operator
annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Deep Insights
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed error converting YAML to JSON: yaml: line 5: mapping values are not allowed in this context
      links:
        - name: Github PR
          url: https://github.com/arldka/helm-charts/pull/6
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/arldka/helm-charts       
    - name: kube-prometheus-stack source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  artifacthub.io/crds: |
    - kind: AlertmanagerConfig
      version: monitoring.coreos.com/v1alpha1
      name: alertmanagerconfigs.monitoring.coreos.com
      description: AlertmanagerConfig defines a namespaced AlertmanagerConfig to be aggregated across multiple namespaces configuring one Alertmanager cluster.
    - kind: Alertmanager
      version: monitoring.coreos.com/v1
      name: alertmanagers.monitoring.coreos.com
      description: Alertmanager describes an Alertmanager cluster.
    - kind: PodMonitor
      version: monitoring.coreos.com/v1
      name: podmonitors.monitoring.coreos.com
      description: PodMonitor defines monitoring for a set of pods.
    - kind: Probe
      version: monitoring.coreos.com/v1
      name: probes.monitoring.coreos.com
      description: Probe defines monitoring for a set of static targets or ingresses.
    - kind: Prometheus
      version: monitoring.coreos.com/v1
      name: prometheuses.monitoring.coreos.com
      description: Prometheus defines a Prometheus deployment.
    - kind: PrometheusRule
      version: monitoring.coreos.com/v1
      name: prometheusrules.monitoring.coreos.com
      description: PrometheusRule defines recording and alerting rules for a Prometheus
    - kind: ThanosRuler
      version: monitoring.coreos.com/v1
      name: thanosrulers.monitoring.coreos.com
      description: ThanosRuler defines a ThanosRuler deployment.
    - kind: ServiceMonitor
      version: monitoring.coreos.com/v1
      name: servicemonitors.monitoring.coreos.com
      description: ServiceMonitor defines monitoring for a set of services.
  artifacthub.io/crdsExamples: |
    - apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: example-app
        labels:
          team: frontend
      spec:
        selector:
          matchLabels:
            app: example-app
        endpoints:
        - port: web
    - apiVersion: monitoring.coreos.com/v1
      kind: Prometheus
      metadata:
        name: prometheus
      spec:
        serviceAccountName: prometheus
        serviceMonitorSelector:
          matchLabels:
            team: frontend
        resources:
          requests:
            memory: 400Mi
        enableAdminAPI: false
    - apiVersion: monitoring.coreos.com/v1
      kind: Alertmanager
      metadata:
        name: main
      spec:
        replicas: 3
        resources:
          requests:
            memory: 400Mi
    - apiVersion: monitoring.coreos.com/v1alpha1
      kind: AlertmanagerConfig
      metadata:
        name: config-example
        labels:
          alertmanagerConfig: example
      spec:
        route:
          groupBy: ['job']
          groupWait: 30s
          groupInterval: 5m
          repeatInterval: 12h
          receiver: 'wechat-example'
        receivers:
        - name: 'wechat-example'
          wechatConfigs:
          - apiURL: 'http://wechatserver:8080/'
            corpID: 'wechat-corpid'
            apiSecret:
              name: 'wechat-config'
              key: 'apiSecret'
    - apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        creationTimestamp: null
        labels:
          prometheus: example
          role: alert-rules
        name: prometheus-example-rules
      spec:
        groups:
        - name: ./example.rules
          rules:
          - alert: ExampleAlert
            expr: vector(1)
    - apiVersion: monitoring.coreos.com/v1
      kind: PodMonitor
      metadata:
        name: example-app
      spec:
        selector:
          matchLabels:
            app: example-app
        podMetricsEndpoints:
        - port: web
        namespaceSelector:
          any: true
    - apiVersion: monitoring.coreos.com/v1
      kind: ThanosRuler
      metadata:
        name: thanos-ruler-demo
        labels:
          example: thanos-ruler
        namespace: monitoring
      spec:
        image: quay.io/thanos/thanos
        ruleSelector:
          matchLabels:
            role: my-thanos-rules
        queryEndpoints:
          - dnssrv+_http._tcp.my-thanos-querier.monitoring.svc.cluster.local
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack