apiVersion: v2
name: prometheus-operator
icon: https://raw.githubusercontent.com/prometheus/prometheus.github.io/master/assets/prometheus_logo-cb55bb5c346.png
description: Stripped down version of prometheus-operator to only provision the operator and nothing else based on the kube-prometheus-stack chart. 

type: application

version: 0.1.3

appVersion: "0.58.0"

kubeVersion: ">=1.16.0-0"
home: https://github.com/arldka/helm-charts
keywords:
  - operator
  - prometheus
  - prometheus-operator
annotations:
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Deep Insights
  artifacthub.io/prerelease: "false"
  artifacthub.io/changes: |
    - kind: fixed
      description: Removed the remaining if .Values.enanbled
  artifacthub.io/links: |
    - name: Chart source
      url: https://github.com/arldka/helm-charts       
    - name: kube-prometheus-stack source
      url: https://github.com/prometheus-community/helm-charts
    - name: Upstream Project
      url: https://github.com/prometheus-operator/kube-prometheus
  artifacthub.io/crds: |
    - kind: AlertmanagerConfig
      version: v1alpha1
      name: alertmanagerconfigs.monitoring.coreos.com
      description: AlertmanagerConfig defines a namespaced AlertmanagerConfig to be aggregated across multiple namespaces configuring one Alertmanager cluster.
    - kind: Alertmanager
      version: v1
      name: alertmanagers.monitoring.coreos.com
      description: Alertmanager describes an Alertmanager cluster.
    - kind: PodMonitor
      version: v1
      name: podmonitors.monitoring.coreos.com
      description: PodMonitor defines monitoring for a set of pods.
    - kind: Probe
      version: v1
      name: probes.monitoring.coreos.com
      description: Probe defines monitoring for a set of static targets or ingresses.
    - kind: Prometheus
      version: v1
      name: prometheuses.monitoring.coreos.com
      description: Prometheus defines a Prometheus deployment.
    - kind: PrometheusRule
      version: v1
      name: prometheusrules.monitoring.coreos.com
      description: PrometheusRule defines recording and alerting rules for a Prometheus
    - kind: ThanosRuler
      version: v1
      name: thanosrulers.monitoring.coreos.com
      description: ThanosRuler defines a ThanosRuler deployment.
    - kind: ServiceMonitor
      version: v1
      name: servicemonitors.monitoring.coreos.com
      description: ServiceMonitor defines monitoring for a set of services.
  artifacthub.io/recommendations: |
    - url: https://artifacthub.io/packages/helm/artifact-hub/artifact-hub
    - url: https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack


